[env:ESP32_DIY_2W_LoRa]
extends = env:esp32
board = esp32dev
build_flags =
	${common.build_flags}
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX127X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D ESP32_DIY_LoRa_GPS       ; This triggers the standard BT/GPS logic
	-D BOARD_MAX_POWER=22       ; Sets the 2W ceiling
	-D BLUETOOTH_ACTIVE         ; Force-enables the BT feature
	-I variants/ESP32_DIY_2W_LoRa
lib_deps =
	${common.lib_deps}
	${common.display_libs}
	; Add your specific display if different from common
	adafruit/Adafruit SH110X @ 2.1.10 
